import { createClient } from '@supabase/supabase-js';
import Config from 'react-native-config';

// Initialize Supabase client
export const supabase = createClient(
  Config.SUPABASE_URL || '',
  Config.SUPABASE_ANON_KEY || ''
);

// Database types (will be generated by Supabase CLI)
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string;
          handle: string;
          bio?: string;
          home_geo?: any; // PostGIS geography type
          terms_version: number;
          terms_accepted_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name: string;
          handle: string;
          bio?: string;
          home_geo?: any;
          terms_version: number;
          terms_accepted_at: string;
        };
        Update: {
          display_name?: string;
          handle?: string;
          bio?: string;
          home_geo?: any;
          terms_version?: number;
          terms_accepted_at?: string;
        };
      };
      vehicles: {
        Row: {
          id: string;
          user_id: string;
          vin?: string;
          make: string;
          model: string;
          year: number;
          trim?: string;
          specs?: any;
          photos: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          vin?: string;
          make: string;
          model: string;
          year: number;
          trim?: string;
          specs?: any;
          photos?: string[];
        };
        Update: {
          vin?: string;
          make?: string;
          model?: string;
          year?: number;
          trim?: string;
          specs?: any;
          photos?: string[];
        };
      };
      // Add other table types as needed
    };
  };
}

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Inserts<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type Updates<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];