version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dash
    ports:
      - "5432:5432"
    volumes:
      - dash_pg:/var/lib/postgresql/data
volumes:
  dash_pg:
